services:
  proxy:
    image: nginx:alpine
    environment:
      NGINX_HOST: foobar.com
    volumes:
      - ./data/configs/proxy.conf:/etc/nginx/conf.d/proxy.conf:ro
      - ./data/volumes/proxy-certs:/etc/nginx/certs:ro
    ports:
      - 80:80
      - 443:443
    networks:
      proxy-internal:
      external:
    restart: unless-stopped


  database:
      image: postgres:alpine
      environment:
        POSTGRES_PASSWORD_FILE: /run/secrets/db-password
      secrets:
        - db-password
      volumes:
        - ./static/database/init.sh:/init.sh:ro
        - ./data/volumes/database:/var/lib/postgresql/data
      networks:
        db-internal:
      restart: unless-stopped
      healthcheck:
        test: [ "CMD-SHELL", "sh -c 'pg_isready -U postgres -d postgres'" ]
        interval: 10s
        timeout: 3s
        retries: 3
        

networks:
  proxy-internal:
    internal: true
  db-internal:
    internal: true
  external:

secrets:
  db-password:
    file: ./secrets/db-password.txt